### ISSUE TITLE
grid visual bug after calibration

### ISSUE THREAD

**Issue by dunland** [dunland/q100_viz#5]
grid seemingly not updated after hitting arrow files.. image transforms well, no duplications visible

![Screenshot from 2021-06-08 11-20-09](https://user-images.githubusercontent.com/23742320/121159643-a28a3100-c84b-11eb-84d6-123c12a2d543.png)

**Comment by dunland** [comment]
similarly, the stroke of the grid cells does not update (back to 1 when deselecting)

**Comment by janbehrens** [comment]
Fixed in d5ac800.

**Comment by dunland** [comment]
funktioniert!
